- hosts: vm
  tasks:
    - name: set root .my.cnf
      blockinfile:
        path: /root/.my.cnf
        owner: root
        group: root
        mode: 0600
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK #"
        block: |
          [client]
          user = root
          password = {{ db_root_pass }}
      vars:
        db_root_pass: "{{ vault_db_root_pass }}"