pkgs:
  - rsyslog
  - composer
  - cronie
  - fping
  - git
  - ImageMagick
  - jwhois
  - mariadb
  - mariadb-server
  - mtr
  - MySQL-python
  - net-snmp
  - net-snmp-utils
  - nginx
  - nmap
  - php72w
  - php72w-cli
  - php72w-common
  - php72w-curl
  - php72w-fpm
  - php72w-gd
  - php72w-mbstring
  - php72w-mysqlnd
  - php72w-process
  - php72w-snmp
  - php72w-xml
  - php72w-zip
  - python-memcached
  - rrdtool
  - php-pear